name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: axel-op/googlejavaformat-action@v3
        with:
          version: 1.16.0
          args: "--aosp --skip-sorting-imports --skip-reflowing-long-strings --skip-javadoc-formatting --replace"
      - name: Set git credentials
        run: |
          git config user.email "tgrothe@users.noreply.github.com"
          git config user.name "tgrothe"
      - name: Del previous builds
        run: |
          git rm target/mp3-wrapper-for-yt-dlp-1.0.*.jar -f
          git commit -m "Automatically del previous builds"
      - name: Build with Maven
        run: mvn -B clean compile assembly:single --file pom.xml
      - name: Upload
        run: |
          git add target/mp3-wrapper-for-yt-dlp-1.0.*.jar -f
          git commit -m "Automatically build upload"
          git push
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
