name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            pom:
              - 'pom.xml'
            src:
              - 'src/**'
      - uses: actions/checkout@v3
        if: steps.changes.outputs.pom == 'true' && steps.changes.outputs.src == 'true'
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 17
        if: steps.changes.outputs.pom == 'true' && steps.changes.outputs.src == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: axel-op/googlejavaformat-action@v3
        if: steps.changes.outputs.pom == 'true' && steps.changes.outputs.src == 'true'
        with:
          version: v1.16.0
          # --skip-sorting-imports
          args: "--aosp --skip-reflowing-long-strings --skip-javadoc-formatting --replace"
      - name: Build with Maven
        if: steps.changes.outputs.pom == 'true' && steps.changes.outputs.src == 'true'
        run: |
          mvn -B clean compile assembly:single --file pom.xml
      - name: Upload build
        if: steps.changes.outputs.pom == 'true' && steps.changes.outputs.src == 'true'
        run: |
          git config user.email "tgrothe@users.noreply.github.com"
          git config user.name "tgrothe"
          git add .
          git commit -m "Automatically build upload"
          git push
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
